version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - ./leetcode.db:/app/leetcode.db

  frontend:
    build:
      context: ./led-matrix-sce
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_MAIN_URL=https://sce.sjsu.edu/leetcode/api
      - VITE_API_KEY=${API_KEY}
    depends_on:
      - backend

  emulator:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    ports:
      - "8888:8888"
    volumes:
      - ./RGBMatrixEmulator:/app/RGBMatrixEmulator
    depends_on:
      - backend